### ISSUE TITLE
Fix Sphinx build on readthedocs.org

### ISSUE THREAD

**Issue by exarkun** [twisted/imaginary#42]
It fails now: https://readthedocs.org/builds/imaginary/1427690/

Apparently because `setup.py install` does not actually work for Imaginary unless you already have Epsilon installed.  This is not news - the travis.yml configuration already works around the extremely-early Epsilon dependency.

Probably the thing to do is switch to using setuptools.  Then readthedocs.org might get further into the build process (and the travis configuration can get slightly simpler).

**Comment by glyph** [comment]
I am hoping that the state of the art has moved on here somewhat; I just triggered a build at https://readthedocs.org/projects/imaginary/builds/3707237/ to see if this is still a concern.

**Comment by glyph** [comment]
Nope, still failing. But it's failing *now* because of a missing `.requirements-readthedocs.txt` file.

**Comment by glyph** [comment]
Adding all the relevant requirements from `pip freeze` results in a working build.  This is now fixed!

**Comment by glyph** [comment]
https://github.com/twisted/imaginary/commit/15d7bfc6f2494618be3600a24341977118bb850a being the relevant commit.
