### ISSUE TITLE
Clothing appears to be both on the wearer and in the location where the wearer is.

### ISSUE THREAD

**Issue by ashfall** [twisted/imaginary#7]
If you create an article of clothing, wear it, and then look at your location, you are told that the article of clothing you're wearing is in the location.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-06-11T12:05:30Z
 * owner: exarkun
 * the launchpad url was https://bugs.launchpad.net/bugs/1189881

**Comment by glyph** [comment]
This is resolved with the merge of #34:

```console
$ python -m imaginary
> create shirt named shirt
You create a shirt.
> wear shirt
You put on the shirt.
> look
[ The Place ]

> look at me
[ player ]
player is great.
It is wearing a shirt.
```
